backend:
  name: git-gateway
  branch: main

media_folder: "assets/art"
public_folder: "assets/art"

collections:
  - name: "content"
    label: "Quản lý Nội dung"
    files:
      - label: "Dữ liệu Website"
        name: "data"
        file: "data.json"
        fields:
          - label: "Danh sách Tranh vẽ"
            name: "artData"
            widget: "list"
            summary: "{{title}}"
            fields:
              - {label: "ID (ví dụ: tranh1)", name: "id", widget: "string"}
              - {label: "Tiêu đề", name: "title", widget: "string"}
              - {label: "Ảnh", name: "image", widget: "image"}
              - {label: "Mô tả", name: "description", widget: "text"}
              - {label: "Ngày", name: "date", widget: "datetime", format: "YYYY-MM-DD"}
              - {label: "Link Toyhouse", name: "link", widget: "string", required: false}

          - label: "Danh sách Video"
            name: "videoData"
            widget: "list"
            summary: "{{title}}"
            fields:
              - {label: "Tiêu đề", name: "title", widget: "string"}
              - {label: "Link Embed Youtube", name: "embedUrl", widget: "string"}
              - {label: "Mô tả", name: "description", widget: "string"}